### ISSUE TITLE
New compiled version results in a fault.

### ISSUE THREAD

**Issue by Tadasu85** [themuseblockchain/Muse-JS#1]
OUTPUT::::

Unhandled rejection Error: 10 assert_exception: Assert Exception
a0 != e: too few arguments passed to method
    {}
    th_a  api_connection.hpp:165 call_generic (see err.payload for the full error payload)
    at e.<anonymous> (file:///home/tad/Muse-Smart-App-Proto/muse.min.js:1:11138)
    at e.r.emit (file:///home/tad/Muse-Smart-App-Proto/muse.min.js:1:14121)
    at WebSocket.<anonymous> (file:///home/tad/Muse-Smart-App-Proto/muse.min.js:1:9145)
F @ muse.min.js:2
S @ muse.min.js:2
B @ muse.min.js:2
t._notifyUnhandledRejection @ muse.min.js:2
n._drainQueue @ muse.min.js:2
n._drainQueues @ muse.min.js:2
drainQueues @ muse.min.js:2
Promise resolved (async)
o @ muse.min.js:2
n._queueTick @ muse.min.js:2
i @ muse.min.js:2
c.hasDevTools.n.invokeLater @ muse.min.js:2
t._ensurePossibleRejectionHandled @ muse.min.js:2
o._reject @ muse.min.js:1
o._rejectCallback @ muse.min.js:1
(anonymous) @ muse.min.js:1
(anonymous) @ muse.min.js:1
r.emit @ muse.min.js:1
(anonymous) @ muse.min.js:1

The function works on my previously compiled version of MUSE JS. I will dig into the issue when I get a chance but if someone else gets to it first thatd be awesome for now I will have to use the old version.

**Comment by Tadasu85** [comment]
RAWR!!!


[4:24] 
I just realized why this issue exists


[4:24] 
https://github.com/themuseblockchain/Muse-JS/issues/1
GitHub
New compiled version results in a fault. · Issue #1 · themuseblockchain/Muse-JS
OUTPUT:::: Unhandled rejection Error: 10 assert_exception: Assert Exception a0 != e: too few arguments passed to method {} th_a api_connection.hpp:165 call_generic (see err.payload for the full er...
 


[4:25] 
My changes on my personal repo havent been commited to main repo


[4:25] 
Im gonna submit a PR now

**Comment by Tadasu85** [comment]
Closed by this PR https://github.com/themuseblockchain/Muse-JS/pull/2
